### ISSUE TITLE
Fees should adapt to the order of magnitude

### ISSUE THREAD

**Issue by Catheryne** [blockcypher/explorer#100] opened 2015-03-05 19:45 UTC
Very low fees (eg. microtx) are showing up as 0.0 BTC on the explorer. Can you change it to be adaptive to reflect the actual fee (instead of rounding it to the 10th decimal place)?

**Comment by mflaxman** [comment] 2015-03-08 12:37
Good catch, thanks!

**Comment by mflaxman** [comment] 2015-04-03 03:25
I just pushed a small fix that I think works but it's tricky because different people legitimately want to see different fees. @Catheryne can you take a look when you have some time?

**Comment by matthieu** [comment] 2015-04-03 16:58
Can you use something more like that:

   - if num > 1 BTC -> display in BTC
   - if num > 1 mBTC display in mBTC
   - else display in satoshis

**Comment by mflaxman** [comment] 2015-04-03 17:42
I love that (I've done it on other apps), but the problem is that I think it only works for BTC.

There's no mDOGE/mLTC or LTC/DOGE Satoshis, right?

**Comment by mflaxman** [comment] 2015-04-03 17:44
Also, isn't mBTC being replaced by bits?

https://bitcointalk.org/index.php?topic=592691.0

**Comment by matthieu** [comment] 2015-04-03 17:51
We can do it only for BTC, for others we can stick with long decimals.

Sorry forgot bits, let's use that instead yes.

**Comment by mflaxman** [comment] 2015-04-03 20:00
I don't love the idea of hard-coding a different thing for BTC vs the other cryptos but it's doable and I don't have any better ideas.

Any change for non-BTC or keep that as-is?

I could also do something where everything is formatted as follows:
- 0.0000100 LTC -> 0.00001 LTC
- 0.0000000 LTC -> 0 LTC (or 0.00 LTC)
- 0.0000001 LTC -> 0.0000001 LTC (no change)

So basically, I'd show as much precision as we have but always round away any extra 0s.

Keep in mind none of these are trivial, I'll be writing custom filters/rules. Not hard, but more work than it sounds like.

**Comment by matthieu** [comment] 2015-04-03 20:13
Yeah, I'm not sure those are worth the effort. I'd concentrate on BTC until someone asks for it.

**Comment by mflaxman** [comment] 2015-04-03 20:58
:+1:

**Comment by mflaxman** [comment] 2015-04-19 15:13
note to self: make this also work for widgets

**Comment by matthieu** [comment] 2015-08-22 17:40
More and more people are noticing this and not only for fees, you can actually see inputs or outputs at 0, which is pretty weird. Can I haz adaptive numbers? :)

**Comment by mflaxman** [comment] 2015-08-24 15:26
Ok, first thing after bcwallet goes live!

**Comment by mflaxman** [comment] 2015-09-18 00:52
Closing now as this is (finally!) fixed once this is merged in https://github.com/blockcypher/explorer/commit/897a7903e9d4d015816ed5503c2be12cb79508e7

The solution isn't 100%, since what we really want is to take a number like: `321.234567 BTC received` and turn it into `321.23... BTC received` where you can click the `...` and it expands fully.

If that's the route we want to go, it's straightforward enough to add that onto this.

**Closed** 2015-09-18 00:52 UTC
Labels: enhancement
